### ISSUE TITLE
support of firefox & IE

### ISSUE THREAD

**Issue by jeromew** [adobe-fonts/adobe-blank-2#1]
I have been trying to build a fallback font using https://github.com/behdad/tofudetector and discovered your project after reading https://blogs.adobe.com/CCJKType/2015/04/adobe-blank-2.html

I have had success with the 2 projects (tofudetector & adobe-blank-2) in chrome browser where I can reliably stop the default fallback font mechanism and show a tofu instead (blank in the case of adobe-blank-2).

I could not manage to make it work under firefox & IE on windows.

I am not very font-fluent and thought that maybe in 2016 (tofudetector was discussed in 2014) those engine would accept pure format 13 cmap tables like the one used in tofudetector and adobe-blank-2.

Can I ask if you had success in these engines ? I really don't understand if this is a problem on my part ; a problem in the engines or a problem in the way fonts are generated by tofudetector of adobe-blank-2.

When I use adobe-blank, tofu (blank) is shown as expected under the 3 browsers so this may be related to specific browser / platforms details.

Thanks for your help

**Comment by kenlunde** [comment]
Believe it or not, you sort of answered your own question.

As far as I am aware, the only OS that supports the Format 13 'cmap' subtable is Apple's macOS, and probably Google's Chrome OS. Your results strongly suggest that Windows doesn't support it, which agrees with my understanding of the situation. The Chrome browser on Windows no doubt supports it, which also explains your results. Perhaps @behdad can confirm.

In any case, the reason why [Adobe Blank](https://github.com/adobe-fonts/adobe-blank) and Adobe Blank 2 both exist is precisely because not all environments can consume the Format 13 'cmap' subtable.

**Comment by behdad** [comment]
Humm.  FreeType, and hence Linux, Android, and ChromeOS support format 13 cmap.  So, looks like you mean the only OS NOT supporting them is Windows...

@khaledhosny any idea why Chrome rejects font without post and name tables?  That's quite bogus IMO even if the spec calls them required.

**Comment by behdad** [comment]
Chrome uses HarfBuzz for cmap, so it should work on every platform.

**Comment by behdad** [comment]
CC @jfkthame; AFAIU Firefox does its own cmap as well, so if it's not working, they can look into it.

**Comment by kenlunde** [comment]
@behdad: Thank you for chiming in with additional helpful details, and for confirming that the only modern OS that cannot consume the Format 13 'cmap' subtable is Windows.

**Comment by jeromew** [comment]
Thanks for your help in understanding this. My tests were on windows.
 - chrome browser (latest) indeed works (now I now this is thanks to HarfBuzz)
 - firefox (latest) does not work and have their own implementation
 - IE browser (latest) does not work and probably use some OS level library

I think I made a mistake when I saw the ".eot" files since they usually are used on the web to handle old IE versions. I concluded too early that windows's spec support was ok on format 13 and that the "Note that some environments might not be able to consume OpenType fonts with a Format 13 'cmap' subtable" catch-all sentence was not meant for modern browsers.

Thanks for your time and knowledge.

**Comment by jfkthame** [comment]
On 28/11/2016 12:52, jeromew wrote:
>   * firefox (latest) does not work and have their own implementation

Regarding Firefox, could you please file a bug with testcase at 
https://bugzilla.mozilla.org? Thanks!

Oh, and does it work in Firefox on any other platforms? Do any 
font-related error/warning messages appear in the web console when 
loading the testcase?

**Comment by jeromew** [comment]
@jfkthame created ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1320665

I did not test on other platforms. Under windows, the firefox developer console does not have any font-related error/warning.

**Comment by khaledhosny** [comment]
> @khaledhosny any idea why Chrome rejects font without post and name tables? That's quite bogus IMO even if the spec calls them required.

Right now OTS [considers `post` and `name` tables required](https://github.com/khaledhosny/ots/blob/master/src/ots.cc#L88), this might be excessive but I wonder what would happen if you feed GDI/DirectWrite/Core Text with a font missing these tables. We probably can generate some dummy tables in case they are missing and accept such fonts.
